pretext: ""
title: CE417
description: Sharif University of Technology Artificial Intelligence course
university: Sharif University of Technology
course: Artificial Intelligence course
authors: Ahmad Salimi, Hamila Mailee

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+

github_url: https://github.com/SUT-AI
telegram_url: https://t.me/AP98SUT
quera_url: https://quera.ir/overview/add_to_course/course/7773/
